[build]
  command = "npm run build"
  publish = "dist"

# This redirect rule is crucial for React Apps (Single Page Apps)
# It directs all traffic to index.html so routing works on refresh
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200